services:
  - type: web
    name: lung-disease-classifier
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libsndfile1
      pip install -r requirements.txt
    startCommand: python app.py
